// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/impact-variants/BentoGrid.tsx": () => import("../components/mockups/impact-variants/BentoGrid.tsx"),
  "./components/mockups/impact-variants/MagazineGrid.tsx": () => import("../components/mockups/impact-variants/MagazineGrid.tsx"),
  "./components/mockups/impact-variants/ProgressBars.tsx": () => import("../components/mockups/impact-variants/ProgressBars.tsx")
};
